#
# Website configuration flags
#

# Name of the site
name: Sage Math Cloud tutorial
description: A tutorial for anyone wanting to use SageMathCloud for teaching

# Includes an icon in the footer for each username
# Includes an icon in the footer for each username you enter
footer-links:
  github: trallard

# Since the site is hosted at a Projectrepository
# (http://username.github.io/repository)
# the baseurl needs to be added ("/repository")
baseurl: "/SMC_tutorial"

permalink: /:title/

# SASS directory for @IMPORTS
sass:
  style :compressed #can use expanded instead

# Plug-ins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Base Jekyll-theme
theme: jekyll-theme-slate
