# Site settings
title: CoCalc tutorial
motto: A tutorial for anyone wanting to use CoCalc for teaching
description: A tutorial for anyone wanting to use CoCalc for teaching
baseurl: "/cocalc_tutorial"
url: "https://tutorial.cocalc.com" # the base hostname & protocol for your site

footer-links:
  github: mikecroucher
  twitter: rse_sheffield
  email: rse@sheffield.ac.uk

# Build settings
markdown: kramdown

# Additional gems
gems:
  - jekyll-titles-from-headings
