# Site settings
title: SageMath Cloud tutorial
motto: A tutorial for anyone wanting to use Sage Math Cloud for teaching
description: -----
baseurl: "/SMC_tutorial"
url: "http://mikecroucher.github.io" # the base hostname & protocol for your site

footer-links:
  github: mikecroucher
  twitter: rse_sheffield
# Build settings
markdown: kramdown
