# Site settings
title: SageMath Cloud tutorial
motto: A tutorial for anyone wanting to use Sage Math Cloud for teaching
description: -----
baseurl: "/SMC_tutorial"
url: "http://trallard.github.io/SMC_prueba-" # the base hostname & protocol for your site

footer-links:
  github: trallard
  twitter: walkingrandomly
# Build settings
markdown: kramdown
