# Site settings
title: SageMathCloud tutorial
motto: A tutorial for anyone wanting to use SageMathCloud for teaching
description: A tutorial for anyone wanting to use SageMathCloud for teaching
baseurl: "/SMC_tutorial/"
url: "http://mikecroucher.github.io" # the base hostname & protocol for your site

footer-links:
  github: mikecroucher
  twitter: rse_sheffield
  email: rse@sheffield.ac.uk

# Build settings
markdown: kramdown

# Additional gems
gems:
  - jekyll-titles-from-headings

include: ['_pages']

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true
