#
# Website configuration flags
#

# Name of the site
name: SMC tutorial

# Includes an icon in the footer for each username
# Includes an icon in the footer for each username you enter
footer-links:
  github: trallard

# Since the site is hosted at a Projectrepository
# (http://username.github.io/repository)
# the baseurl needs to be added ("/repository")
baseurl: "/SMC_tutorial"

# Exclude these files
exclude:
  - LICENSE

# Base Jekyll-theme
theme: jekyll-theme-slate
